name: Trivy Scan

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true

permissions:
  contents: read

jobs:
  trivy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read

    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: docker load -i image.tar

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.docker_username }}/hello-python:${{ inputs.image_tag }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH